baseURL = 'http://tiagopbrodrigues.com/'
languageCode = 'en-us'
title = "Hey guys, I'm Tiago"
theme = "hello-friend-ng"
paginate = 10

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "This is my little corner of the internet"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My new personal page and blog, all in one"
  keywords = "blog, personal, resume"
  images = [""]

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hey guys, I'm Tiago"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [params.portrait]
    path = "./img/profile-big.jpg"
    alt = "Portrait"

  [[params.social]]
    name = "github"
    url  = "https://github.com/1Krypt0"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/tiago-rodrigues-221ba7204/"

  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/tiagorodrigues.01/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/thekrypt0"

  [[params.social]]
    name = "email"
    url  = "mailto:tiagopbr.2001@gmail.com"


  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/posts/about"
